version: '2'
mpp-vars:
  name: container
  use_containers: true
pipelines:
- mpp-import-pipelines:
    path: include/build.ipp.yml
- name: rootfs
  build: name:build
  stages:
  - type: org.osbuild.kernel-cmdline
    options:
      root_fs_uuid:
        mpp-eval: rootfs_uuid
      kernel_opts:
        mpp-eval: ''' '' .join(kernel_opts)'
  - type: org.osbuild.rpm
    options:
      gpgkeys:
      - mpp-eval: centos_gpg_key
      - mpp-eval: redhat_gpg_key
      disable_dracut: true
    inputs:
      packages:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-depsolve:
          architecture: $arch
          ignore-weak-deps: true
          module-platform-id: $distro_module_id
          baseurl: $distro_baseurl/BaseOS/$arch/os/
          repos:
            mpp-join:
            - mpp-eval: image_repos
            - mpp-eval: extra_repos
            - - id: copr-hirte-snapshot
                baseurl: https://download.copr.fedorainfracloud.org/results/mperina/hirte-snapshot/centos-stream-9-$arch
            - - id: podman-next
                baseurl: https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/centos-stream+epel-next-9-$arch/
          packages:
            mpp-join:
            - mpp-eval: image_rpms
            - mpp-eval: extra_rpms
            - - podman
              - containernetworking-plugins
              - curl
              - hirte
              - qm
          excludes:
          - dracut-config-rescue
  - type: org.osbuild.users
    options:
      users:
        guest:
          password:
            mpp-eval: guest_password
          gid:
            mpp-eval: guest_gid
          uid:
            mpp-eval: guest_uid
- mpp-import-pipelines:
    path: include/image.ipp.yml
